[General]
currentUserName=rtinfew
diskUsage=20
hidePassword=false
isRevealed=false
lastAudioJson="{\"outputs\": [{\"id\": \"55\", \"name\": \"alsa_output.pci-0000_00_1f.3.analog-stereo\", \"description\": \"Built-in Audio\", \"volume\": 14, \"mute\": false, \"is_default\": true, \"icon\": \"audio-card-analog\"}], \"inputs\": [{\"id\": \"56\", \"name\": \"alsa_input.pci-0000_00_1f.3.analog-stereo\", \"description\": \"Built-in Audio\", \"volume\": 27, \"mute\": false, \"is_default\": true, \"icon\": \"audio-card-analog\"}], \"apps\": []}"
lastBtJson="{\"present\":true,\"power\":\"off\",\"connected\":[],\"devices\":[]}"
lastEthJson="{\"present\":true,\"power\":\"off\",\"device\":\"enp0s31f6\",\"connected\":null}"
lastName=
lastWifiJson="{\"present\":true,\"power\":\"on\",\"connected\":null,\"networks\":[{\"id\":\"TIEN VINH\",\"ssid\":\"TIEN VINH\",\"icon\":\"󰤨\",\"signal\":\"97\",\"security\":\"WPA1 WPA2\"},{\"id\":\"[LG_Wall-Mount A/C]de78\",\"ssid\":\"[LG_Wall-Mount A/C]de78\",\"icon\":\"󰤨\",\"signal\":\"92\",\"security\":\"WPA2\"},{\"id\":\"Thien Truc\",\"ssid\":\"Thien Truc\",\"icon\":\"󰤢\",\"signal\":\"59\",\"security\":\"WPA1 WPA2\"}]}"
lastWifiSsid=
powerProfile=balanced
query=
revealDuration=300
searched=false
sessionId=0
sysBrightness=100
sysMuted=false
sysVolume=14
upHours=0
upMins=0
