[GraphNodePos]
PulseAudio%20Volume%20Control=@Variant(\0\0\0\x1a@`\0\0\0\0\0\0\xc0X\0\0\0\0\0\0)
PulseAudio%20Volume%20Control-1=@Variant(\0\0\0\x1a@_\0\0\0\0\0\0\xc0g\x80\0\0\0\0\0)
PulseAudio%20Volume%20Control-2=@Variant(\0\0\0\x1a@H\0\0\0\0\0\0\xc0g\0\0\0\0\0\0)
