foreground              #e1e2e9
background              #1d2024
selection_foreground    #d9e3f8
selection_background    #3d4758

cursor                  #a7c8ff
cursor_text_color       #04305f

url_color               #dbbce1

active_border_color     #a7c8ff
inactive_border_color   #43474e
bell_border_color       #ffb4ab

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #d5e3ff
active_tab_background   #244777
inactive_tab_foreground #c4c6cf
inactive_tab_background #1d2024
tab_bar_background      #111318

mark1_foreground #04305f
mark1_background #a7c8ff
mark2_foreground #273141
mark2_background #bdc7dc
mark3_foreground #3e2845
mark3_background #dbbce1

color0 #43474e
color8 #8e9199

color1 #ffb4ab
color9 #93000a

color2  #a7c8ff
color10 #d5e3ff

color3  #dbbce1
color11 #f8d8fe

color4  #bdc7dc
color12 #d9e3f8

color5  #244777
color13 #3e5f90

color6  #3d4758
color14 #563e5d

color7  #c4c6cf
color15 #e1e2e9
